# Generated by Django 4.0.3 on 2022-03-18 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountPointSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=256)),
                ('branch', models.CharField(max_length=256)),
                ('office_branch', models.CharField(blank=True, max_length=256)),
                ('bill_number', models.CharField(blank=True, max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2022, 3, 18, 16, 58, 2, 22265))),
                ('mobile_number', models.BigIntegerField(blank=True)),
                ('customer', models.CharField(blank=True, max_length=256)),
                ('card_number', models.CharField(blank=True, max_length=256)),
                ('bill_amount', models.FloatField(blank=True)),
                ('points', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RewardPointSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=256)),
                ('branch', models.CharField(max_length=256)),
                ('office_branch', models.CharField(blank=True, max_length=256)),
                ('bill_number', models.CharField(blank=True, max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2022, 3, 18, 16, 58, 2, 21290))),
                ('mobile_number', models.BigIntegerField(blank=True)),
                ('customer', models.CharField(blank=True, max_length=256)),
                ('card_number', models.CharField(blank=True, max_length=256)),
                ('bill_amount', models.FloatField(blank=True)),
                ('points', models.FloatField(blank=True)),
            ],
        ),
    ]
