# Generated by Django 3.2.6 on 2022-04-17 11:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220403_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=300, unique=True)),
                ('office', models.CharField(max_length=256)),
                ('branch', models.CharField(max_length=256)),
                ('office_branch', models.CharField(blank=True, max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2022, 4, 17, 11, 7, 34, 484256, tzinfo=utc))),
                ('customer_name', models.CharField(blank=True, max_length=256)),
                ('number', models.BigIntegerField()),
                ('alt_number', models.BigIntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('card_number', models.CharField(max_length=256)),
                ('date_for_BA', models.CharField(blank=True, max_length=9)),
                ('birt_anny', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='discountpointsystem',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 11, 7, 34, 482257, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rewardpointsystem',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 11, 7, 34, 480335, tzinfo=utc)),
        ),
    ]
