# Generated by Django 3.2.6 on 2022-04-17 18:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220417_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='date_for_BA',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 18, 25, 51, 613215, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='discountpointsystem',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 18, 25, 51, 611218, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rewardpointsystem',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 18, 25, 51, 608528, tzinfo=utc)),
        ),
    ]
